server:
  port: 8080

jwt:
  issuer: auth-service
  expiration: 864000000
  private-key: classpath:private-key.pem
  public-key: classpath:public-key.pem

internal:
  secret: my-ultra-secure-internal-key

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: postgres
    password: root

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer